---
title: "crick"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cricket <- read.csv(file = "D:/Data Science 2017/Manipal Academy of Data Science/MGADS TERM2/2 Data Visualization/odi-batting.csv")
cricket
```

```{r}
library(dplyr)
```

```{r}
sach_score <- cricket %>% filter(Player=="Sachin R Tendulkar")
sach_score
```

```{r}
ggplot(sach_score,aes(x=Runs,y=ScoreRate)) + geom_point() + geom_smooth()

```

```{r}
top_players <- c("Sachin R Tendulkar","Mahendra S Dhoni","Sourav C Ganguly")
sach_score1 <- cricket %>% filter(Player %in% top_players)
sach_score1
```
```{r}
ggplot(sach_score1,aes(x=Runs,y=ScoreRate,color=Player)) + geom_smooth()
```

```{r}
top10players <- cricket %>% group_by(Player) %>% summarize(totalruns = sum(Runs,na.rm=TRUE)) %>% arrange(-totalruns) %>% head(10)
top10players
```

```{r}
top_players <- cricket %>% filter(Player %in% top10players$Player)
top_players
```
```{r}
ggplot(top_players ,aes(x=Runs , y=ScoreRate,color=Player)) + geom_smooth()
```

```{r}
cricket <- cricket %>%mutate(Year= format(as.Date(cricket$MatchDate,'%m-%d-%Y'),'%Y'))
View(cricket)
```

```{r}
cricket <- cricket %>% mutate(century=if_else(Runs >= 100,1,0))
View(cricket)
```

```{r}
year_data <- cricket %>% group_by(Year) %>% filter(Player=="Ricky T Ponting") %>% summarize(runs=sum(Runs),centuries=sum(century))
year_data
```
```{r}
install.packages("plotly")
library(plotly)
```

```{r}
r<- ggplot(year_data,aes(x=Year,y= runs, size=centuries)) +  geom_point()
ggplotly(r)
```

